Try using SHA256 for git narHash
currently not working, fails with:

  error: Git file ingestion must use sha1 hash

Might need to prevent narHash being used to calculate store paths in
some place.